#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Delete all resrouces including Hazelcast, PadoGrid and Ingress

SYNOPSIS
   $EXECUTABLE [-oss] [-all] [-?]

DESCRIPTION
   Deletes all resrouces including Hazelcast, PadoGrid, Ingress, Prometheus, and Grafana.
   To delete persistent claims and 'local-storage' specify the '-all' option.

   Note that this command does not delete Kubernetes Dashboard. To delete Kubernetes,
   Dashboard, run './stop_dashboard'.

OPTIONS
   -oss
             If specified, then deletes Hazelcast OSS resources, otherwise, Hazelcast Enterprise resources.

   -all
             If specified, then deletes all resources including the persistent claims and 'local-storage'.

EOF
exit
fi

# Delete PadoGrid
./stop_padogrid "$@"

# Delete Hazelcast
./stop_hazelcast "$@"

# Delete Prometheus, Grafana
./stop_monitor "$@"

echo "Deleting ingress..."
./stop_ingress "$@"

echo ""
echo "Cleanup complete."
