#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Login to the PadoGrid pod

SYNOPSIS
   $EXECUTABLE [paodgrid_pod_name] [-?]

OPTIONS
   padogrid_pod_name
             PadoGrid pod name. If not specified, then the pod name that begins with 'padogrid-1' is assigned.

DESCRIPTION
   Logs in to the PadoGrid pod.

EOF
exit
fi

CURRENT_PROJECT=$(kubectl config get-contexts |grep "*" | awk '{print $5}')
if [ "$CURRENT_PROJECT" != "$NAMESPACE" ]; then
   kubectl config set-context --current --namespace=$NAMESPACE
fi

POD_NAME="$1"
if [ "$POD_NAME" == "" ]; then
   POD_NAME="$(kubectl get pods |grep padogrid | grep -v deploy | sed 's/ .*//')"
fi
if [ "$POD_NAME" == "" ]; then
   echo  >&2 "ERROR: PadoGrid pod not found in this project. Please see the usage. Command aborted."
   exit 1
fi

kubectl exec -it $POD_NAME -- /bin/bash
