apiVersion: v1
kind: PersistentVolume
metadata:
  name: jar-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/custom"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jar-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
